cuda: true
data_params:
  action_ngram_pad: 40
  action_pad: 400
  num_workers: 4
  pin_memory: false
  root_dir: data
  test:
    batch_size: 15
    dry_run: false
    shuffle: true
  token_pad: 150
  train:
    batch_size: 15
    dry_run: false
    shuffle: true
  valid:
    batch_size: 15
    dry_run: false
    shuffle: false
device: cuda
exp_params:
  manual_seed: 1265
  optimizer_params:
    lr: 1.0e-05
  optimizer_type: Adam
  scheduler_params:
    factor: 0.1
    mode: min
    patience: 0
  scheduler_type: ReduceLROnPlateau
logging_params:
  save_dir: ./experiment_checkpoints/eval/gpt2-xl/
  version: layer_28
pretrained_model: gpt2-xl
probe_params:
  add_root: true
  checkpoint_path: experiment_checkpoints/eval/gpt2-xl/Geometric_Action/layer_28/checkpoints/last.ckpt
  data_sources:
  - action_ids
  - gold_tuples
  - gold_distances
  - gold_depths
  - xpos
  embeddings_dropout_rate: 0
  layer: 28
  layer_dropout_rate: 0.2
  loss_types:
  - oracle_action_nll
  num_layers: 1
  oracle_params:
    mappings_file: data/mappings-ptb.txt
    name: ArcStandard
  probe_name: Geometric_Action
  probe_type: GeometricProbe
  temp: 0.1
  threshold: 1.5
  verbose: false
trainer_params:
  accumulate_grad_batches: 1
  gpus:
  - 1
  max_epochs: 25
